import { FlagSpec } from './schema';

export const flags: FlagSpec[] = [
  {
    id: 'trans-pride',
    displayName: 'Trans Pride',
    svgFilename: 'Transgender_Pride_flag.svg',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Transgender_flags' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#5BCEFA', weight: 1, label: 'light blue' },
        { color: '#F5A9B8', weight: 1, label: 'light pink' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#F5A9B8', weight: 1, label: 'light pink' },
        { color: '#5BCEFA', weight: 1, label: 'light blue' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'ua',
    displayName: 'Ukraine',
    category: 'national',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Flag_of_Ukraine' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#0057B7', weight: 1, label: 'blue' },
        { color: '#FFD700', weight: 1, label: 'yellow' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'nk',
    displayName: 'North Korea',
    svgFilename: 'Flag_of_North_Korea.svg',
    category: 'national',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/North_Korea' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#034DA2', weight: 1, label: 'blue' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#EC1D25', weight: 1, label: 'red' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#EC1D25', weight: 1, label: 'red' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'cn',
    displayName: 'China',
    svgFilename: 'Flag_of_China.svg',
    category: 'national',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Politics_of_China' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#EE1C25', weight: 3, label: 'red' },
        { color: '#FFFF00', weight: 1, label: 'gold' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'er',
    displayName: 'Eritrea',
    svgFilename: 'Flag_of_Eritrea.svg',
    category: 'national',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Eritrea' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#E4002B', weight: 1, label: 'red' },
        { color: '#43B02A', weight: 1, label: 'green' },
        { color: '#418FDE', weight: 1, label: 'blue' },
        { color: '#FFC72C', weight: 1, label: 'gold' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'ir',
    displayName: 'Iran',
    svgFilename: 'Flag_of_Iran.svg',
    category: 'national',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Iran' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#DA0000', weight: 1, label: 'red' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#239F40', weight: 1, label: 'green' },
        { color: '#DA0000', weight: 1, label: 'red' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'ps',
    displayName: 'Palestine',
    svgFilename: 'Flag_of_Palestine.svg',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Palestine' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#009639', weight: 1, label: 'green' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#ED2E38', weight: 1, label: 'red' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'tibet',
    displayName: 'Tibet (Snow Lion Flag)',
    svgFilename: 'Flag_of_Tibet.svg',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Flag_of_Tibet' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#F4E109', weight: 1, label: 'yellow' },
        { color: '#DA251C', weight: 1, label: 'red' },
        { color: '#29166F', weight: 1, label: 'deep blue' },
        { color: '#F4E109', weight: 1, label: 'yellow' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#DA251C', weight: 1, label: 'red' },
        { color: '#F1C700', weight: 1, label: 'gold' },
        { color: '#E87817', weight: 1, label: 'orange' },
        { color: '#29166F', weight: 1, label: 'deep blue' },
        { color: '#E87817', weight: 1, label: 'orange' },
        { color: '#29166F', weight: 1, label: 'deep blue' },
        { color: '#E0609B', weight: 1, label: 'pink' },
        { color: '#E87817', weight: 1, label: 'orange' },
        { color: '#E12211', weight: 1, label: 'red' },
        { color: '#F1C700', weight: 1, label: 'gold' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#E12211', weight: 1, label: 'red' },
        { color: '#F1C700', weight: 1, label: 'gold' },
        { color: '#E12211', weight: 1, label: 'red' },
        { color: '#E87817', weight: 1, label: 'orange' },
        { color: '#29166F', weight: 1, label: 'deep blue' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#E87817', weight: 1, label: 'orange' },
        { color: '#29166F', weight: 1, label: 'deep blue' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#F4E109', weight: 1, label: 'yellow' },
        { color: '#E87817', weight: 1, label: 'orange' },
        { color: '#F4E109', weight: 1, label: 'yellow' },
        { color: '#000000', weight: 1, label: 'black' },
        { color: '#F4E109', weight: 1, label: 'yellow' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#84BE86', weight: 1, label: 'green' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#F4E109', weight: 1, label: 'yellow' },
        { color: '#93AA5E', weight: 1, label: 'green' },
        { color: '#F1C700', weight: 1, label: 'gold' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#84BE86', weight: 1, label: 'green' },
        { color: '#93AA5E', weight: 1, label: 'green' },
        { color: '#DA251C', weight: 1, label: 'red' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#F4E109', weight: 1, label: 'yellow' },
        { color: '#000000', weight: 1, label: 'black' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'ws',
    displayName: 'Western Sahara',
    svgFilename: 'Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Western_Sahara' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#000000', weight: 1, label: 'black' },
        { color: '#007A3D', weight: 1, label: 'green' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#C4111B', weight: 1, label: 'red' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#C4111B', weight: 1, label: 'red' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'kurdistan',
    displayName: 'Kurdistan',
    svgFilename: 'Flag_of_Kurdistan.svg',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Kurdistan' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#ED2024', weight: 1, label: 'red' },
        { color: '#278E43', weight: 1, label: 'green' },
        { color: '#FEBD11', weight: 1, label: 'gold' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'uyghur',
    displayName: 'East Turkestan (Uyghur)',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Uyghurs' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#1E90FF', weight: 1, label: 'sky blue' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'rohingya',
    displayName: 'Rohingya',
    svgFilename: 'Rohingya_flag.svg',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Rohingya' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#D4AC34', weight: 1, label: 'gold' },
        { color: '#FBFBFA', weight: 1, label: 'off-white' },
        { color: '#14642C', weight: 1, label: 'green' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
  {
    id: 'pride',
    displayName: 'Pride (Rainbow)',
  svgFilename: 'Gay_Pride_Flag.svg',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Rainbow_flag' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#F00000', weight: 1, label: 'red' },
        { color: '#F09000', weight: 1, label: 'orange' },
        { color: '#F0F000', weight: 1, label: 'yellow' },
        { color: '#00C000', weight: 1, label: 'green' },
        { color: '#3060F0', weight: 1, label: 'blue' },
        { color: '#9000F0', weight: 1, label: 'purple' },
        { color: '#B57EDC', weight: 1, label: 'lavender' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12, primaryColor: '#E40303' },
  },
  {
    id: 'indigenous',
    displayName: 'Indigenous (Generic)',
    category: 'marginalized',
    sources: { referenceUrl: 'https://en.wikipedia.org/wiki/Indigenous_peoples' },
    status: 'active',
    pattern: {
      type: 'stripes',
      orientation: 'horizontal',
      stripes: [
        { color: '#000000', weight: 1, label: 'black' },
        { color: '#FFFFFF', weight: 1, label: 'white' },
        { color: '#FFD700', weight: 1, label: 'yellow' },
        { color: '#D72638', weight: 1, label: 'red' },
      ],
    },
    recommended: { borderStyle: 'ring-stripes', defaultThicknessPct: 12 },
  },
];
